title: Tran Nhut Minh Tam
logo: /assets/img/logo.png
description: A portfolio showcasing my skills, projects, and experience in software development.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
